-- ============================================================
--  Supabase Cloud Database Schema & Initial Data for Meeting Room
-- ============================================================

-- 1. Create Table: rooms
CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  capacity INT NOT NULL,
  location TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'available',
  equipment TEXT[] DEFAULT '{}',
  image TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Table: bookings
CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE CASCADE,
  room_name TEXT NOT NULL,
  user_name TEXT NOT NULL,
  user_tel TEXT NOT NULL,
  booking_date DATE NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  title TEXT NOT NULL,
  headcount INT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Enable RLS (Row Level Security) and public read/write policies
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read rooms" ON rooms FOR SELECT USING (true);
CREATE POLICY "Allow public insert rooms" ON rooms FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update rooms" ON rooms FOR UPDATE USING (true);

CREATE POLICY "Allow public read bookings" ON bookings FOR SELECT USING (true);
CREATE POLICY "Allow public insert bookings" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update bookings" ON bookings FOR UPDATE USING (true);

-- 4. Seed Initial Rooms
INSERT INTO rooms (name, capacity, location, status, equipment, image, description) VALUES
  ('ห้องประชุม Innovation Lab (101)', 12, 'ชั้น 1 อาคารเทคโนโลยี', 'available', ARRAY['โปรเจกเตอร์ 4K', 'Smart TV 75"', 'ไมโครโฟนไร้สาย'], 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80', 'ห้องประชุมขนาดกลาง ตกแต่งสไตล์โมเดิร์น'),
  ('ห้องประชุม Executive Boardroom (201)', 25, 'ชั้น 2 อาคารอำนวยการ', 'available', ARRAY['ระบบ Video Conference', 'ลำโพงรอบทิศทาง', 'TV OLED 85"'], 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&q=80', 'ห้องประชุมระดับผู้บริหาร รองรับการประชุมทางไกล'),
  ('ห้องสัมมนา Auditorium (301)', 60, 'ชั้น 3 อาคารหอประชุม', 'available', ARRAY['เวทีและโพเดียม', 'ไมค์ลอย 4 ตัว', 'ระบบไฟดิมเมอร์'], 'https://images.unsplash.com/photo-1544928147-79a2dbc1f389?auto=format&fit=crop&w=800&q=80', 'ห้องสัมมนาขนาดใหญ่ เหมาะสำหรับอบรมและเวิร์กช็อป'),
  ('ห้องประชุม Creative Hub (102)', 8, 'ชั้น 1 อาคารเทคโนโลยี', 'occupied', ARRAY['Smart Board สัมผัส', 'โซฟาสบาย', 'โต๊ะปรับระดับ'], 'https://images.unsplash.com/photo-1577412647305-991150c7d163?auto=format&fit=crop&w=800&q=80', 'ห้องประชุมขนาดเล็กบรรยากาศเป็นกันเอง'),
  ('ห้องประชุม Tech Focus (202)', 15, 'ชั้น 2 อาคารอำนวยการ', 'available', ARRAY['Dual Monitor Display', 'ปลั๊กไฟทุกที่นั่ง', 'LAN 1Gbps'], 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80', 'ห้องประชุมสำหรับสายไอทีและการพัฒนาซอฟต์แวร์');
